apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName | dump }}
  description: ${{ values.description | dump }}
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
  system: ${{ values.namespace | dump }}
