{{- if and .Values.secrets (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-secrets
  namespace: {{ include "backstage.namespace" . }}
type: Opaque
stringData:
  K8S_SERVICE_ACCOUNT_TOKEN: {{ .Values.secrets.k8sServiceAccountToken | quote }}
  K8S_CA_DATA: {{ .Values.secrets.k8sCaData | quote }}
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
  AUTH_GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
{{- end }}
