{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-secrets
  namespace: {{ include "backstage.namespace" . }}
type: Opaque
stringData:
  K8S_SERVICE_ACCOUNT_TOKEN: {{ .Values.secrets.k8sServiceAccountToken | quote }}
  K8S_CA_DATA: {{ .Values.secrets.k8sCaData | quote }}
  GITHUB_TOKEN: {{ .Values.secrets.githubToken | quote }}
{{- end }}
