apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}-backend
  namespace: {{ include "backstage.namespace" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "backstage.fullname" . }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
