apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-config
  namespace: {{ include "backstage.namespace" . }}
data:
  app-config.kubernetes.yaml: |
    app:
      baseUrl: {{ .Values.global.baseUrl | quote }}

    backend:
      baseUrl: {{ .Values.global.baseUrl | quote }}
      cors:
        origin: {{ .Values.global.baseUrl | quote }}
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          database: ${POSTGRES_DB}

    auth:
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - name: {{ .Values.kubernetes.clusterName | quote }}
              url: {{ .Values.kubernetes.clusterUrl | quote }}
              authProvider: serviceAccount
              serviceAccountToken: ${K8S_SERVICE_ACCOUNT_TOKEN}
              caData: ${K8S_CA_DATA}
