{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.postgresSecretName" . }}
  namespace: {{ include "backstage.namespace" . }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
{{- end }}
