fullnameOverride: backstage

kubernetes:
  clusterName: local-cluster
  clusterUrl: https://192.168.1.200:6443

namespace:
  name: backstage
secrets:
  existingSecret: backstage-secrets
global:
  baseUrl: http://developer-portal.uday.corp
istio:
  enabled: true
  host: developer-portal.uday.corp
postgres:
  auth:
    database: backstage_prod
    existingSecret: backstage-postgres-secret
  persistence:
    storageClassName: longhorn
backend:
  image:
    tag: v0.0.4
frontend:
  image:
    tag: v0.0.4
  nodeSelector:
    kubernetes.io/hostname: worker01
