# Secret para credenciais do PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.name }}
  namespace: {{ include "uday-app.namespace" . }}
  labels:
    app: postgres
type: Opaque
data:
  # Valores codificados em base64
  # user       = base64("user")
  # senha123   = base64("senha123")
  # appdb      = base64("appdb")
  POSTGRES_USER: {{ .Values.secrets.postgres.data.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.data.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.secrets.postgres.data.POSTGRES_DB }}

  # Para gerar novos valores em base64:
  # echo -n "seu_valor" | base64

---
# Secret para JWT do Backend e conexão com o banco de dados
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backend.name }}
  namespace: {{ include "uday-app.namespace" . }}
  labels:
    app: backend
type: Opaque
data:
  # chavejwtsecreta = base64("chavejwtsecreta")
  SECRET_KEY: {{ .Values.secrets.backend.data.SECRET_KEY }}

  # postgresql+psycopg2://user:senha123@postgres-service:5432/appdb
  # = base64("postgresql+psycopg2://user:senha123@postgres-service:5432/appdb")
  DATABASE_URL: {{ .Values.secrets.backend.data.DATABASE_URL }}

  # Para ambientes de produção, gere uma chave segura:
  # python -c "import secrets; print(secrets.token_urlsafe(32))" | base64