apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-runner-argocd
  namespace: argocd
rules:
  - apiGroups: [argoproj.io]
    resources: [applications]
    verbs: [get, list, watch, create, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-runner-argocd
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: github-runner-sa
    namespace: github-runner
roleRef:
  kind: Role
  name: github-runner-argocd
  apiGroup: rbac.authorization.k8s.io
