apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-frontend
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backstage-frontend
    spec:
      containers:
        - name: frontend
          image: registry.uday.corp:5000/backstage-frontend:20260607-1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
