apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.kubernetes.yaml: |
    app:
      baseUrl: https://backstage.local

    backend:
      baseUrl: https://backstage.local
      cors:
        origin: https://backstage.local
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          database: ${POSTGRES_DB}

    auth:
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
