apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgres
  namespace: backstage
type: Opaque
stringData:
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: change-me
  POSTGRES_DB: backstage_plugin_catalog
